/'
## Setup
1. Install graphviz into MacOSX
$ brew install graphviz

2. Install PlantUML integration for IntelliJ
Preferences -> Plugins -> "PlantUML integration"
'/
@startuml{about.png}

title ticket & issue to Jira

package data-flow {

    [AnyToJira] --> [(new) JIRA]

    [Confluence] --> [AnyToJira]
    [Redmine] --> [AnyToJira]
    [(old) JIRA] --> [AnyToJira]
    [Github] --> [AnyToJira]

}

@enduml
